version: "3"
services:
       Webhook:
           container_name: webhook
           image: gwoodford/webhook-tool:latest
           restart: always
           build: .
           ports:
             - "8003:8003"
           links:
             - mongo
           environment: 
             webPort: 8003
             mongoPort: 27019
       mongo:
             container_name: mongo
             image: mongo
             volumes:
               - data:/data/db
             ports:
               - 27019:27019
             command: mongod --port 27019
volumes:
  data:
              